services:
  nghien-phim:
    container_name: nghien-phim
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
        - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
        - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NODE_ENV=production
    env_file:
      - .env
    environment:
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL:?UPSTASH_REDIS_REST_URL is required}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN:?UPSTASH_REDIS_REST_TOKEN is required}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME:?CLOUDINARY_CLOUD_NAME is required}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:?NEXT_PUBLIC_BASE_URL is required}
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - nghien_phim_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  nghien_phim_network:
    driver: bridge
