version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Adjust if package.json is in a subdirectory
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    commit-message:
      prefix: "fix(deps)"
      include: "scope"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "pnpm"  # Prevent Dependabot from updating pnpm itself